### ISSUE TITLE
Contact issue

### ISSUE THREAD

**Issue by trolit** [joeythelantern/DeveloperConsoleUnity#1]
Hi Joey. First of all, thanks for the video on how to make developer console. Found it very useful in app designed for engineering thesis. When app consists of 40 keys and a lot of PlayerPref keys its really powerful in functional testing. I didn't find any ways to contact you via e-mail so decided to submit an issue over here if you don't mind. 

Here's the case. I saw many people having problems with setting their console to use parameters. For engineering thesis I modified it a little covering this and for e.g. automated scrolling. Decided to share the results. Credits are mentioned (link to the repository at the bottom for you to check). If you don't want this to be available I will remove it. 

Thanks once again for the video 👍 

[Repository holding modified console version](https://github.com/trolit/unity-dev-console)

**Comment by joeythelantern** [comment]
Hey Trolit!  Thanks for contacting me here.  I appreciate you opening this ticket, as well as modifying my tutorial to work better with parameters.  I am totally for the community taking what I know and making it even better!

I'll drop a link to your repository as a community link so people can check out your work!

We can chat over discord if you'd like :)
